### ISSUE TITLE
Albedo and latent influence on UTCI

### ISSUE THREAD

**Issue by valentinantonio** [ladybug-tools/dragonfly-uwg#35]
Hi all, 
As part of my studies, I’m currently investigating about Urban Heat Island effect and the different methods to take it into account.
I’m interested in modeling outdoor thermal comfort (through UTCI indicator) for urban planning projects, based on the numerical model and properties of the project
Based on “Urban Microclimate – Simple Spatial UTCI” and "UWG Workflow" files, I tried to run Dragonfly-UWG in order to plot spatial representations of UTCI for urban planing projects.

The idea was to use the epw file modified by urban characteristics to generate the UTCI representation. 
With this in mind, i wanted to evaluate the influence of different parameters such as grass albedo or grass latent.

Here you can see the try i've made: the left part is grass and the right part is pavement with a building. 
![UTCI_gazon2](https://user-images.githubusercontent.com/68389506/88300244-8d73e480-cd03-11ea-844d-2ffdb9621a26.PNG)

As you can notice, there is no difference between the two parts, so i assume the model only takes solar radiation into account... I tried with different values
I don't understand how UWG considers those parameters and how i can do to include it into UTCI calculations. 

I hope I had been precise enough, if not does not hesitate to ask me more information.

Thanks in advance !

Valentin ANTONIO

**Comment by chriswmackey** [comment]
@valentinantonio ,

Questions like this should really go to [our forum]().  If [this is the example you cite](http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Urban_Microclimate_-_Simple_Spatial_UTCI&slide=0&scale=1&offset=0,0), the it's not suing the UWG at all. That example does not account for surface temperature and you want to use a sample like this in order to account for surface temperature:

http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Trees_in_Outdoor_Thermal_Comfort&slide=0&scale=1&offset=0,0
